### ISSUE TITLE
setup.sh error: "bash: /bin/installer: No such file or directory"

### ISSUE THREAD

**Issue by abdullahyildiz** [pulp-platform/pulp-builder#5]
I'm following the instructions at [README.md](https://github.com/pulp-platform/pulp-builder/blob/master/README.md#pulp-sdk-builder).

Running the following command gives an error:

```
source setup.sh
bash: /bin/installer: No such file or directory
```

What can cause such a problem?

**Comment by abdullahyildiz** [comment]
OS version is CentOS Linux release 7.7.1908 (Core).

**Comment by abdullahyildiz** [comment]
Sorry for the question. I noticed that this was because of a PATH setting which belongs to another tool that I have to disable.

**Comment by Arang199** [comment]
1.2 5

**Comment by Arang2747** [comment]
Line 4
