### ISSUE TITLE
Runtime build error

### ISSUE THREAD

**Issue by shillpa-j** [pulp-platform/pulp-builder#6]
Hello...

My GNU compiler tool chain installation is completed. When im trying to build PULP-SDK builder i have installed all the dependencies as mentioned in the GitHub and the process was complete till GVSoC build. When im trying to install the Runtime build error im facing an error which am unable to understand which is as follows

scons: done building targets.
make: Leaving directory '/root/pulpissimo/pulp-builder/hal'
+ make -C pulp-rules all BUILD_DIR=/root/pulpissimo/pulp-builder/build/pulp-rules INSTALL_DIR=/root/pulpissimo/pulp-builder/install/ws TARGET_INSTALL_DIR=/root/pulpissimo/pulp-builder/install
make: Entering directory '/root/pulpissimo/pulp-builder/pulp-rules'
make: Nothing to be done for 'all'.
make: Leaving directory '/root/pulpissimo/pulp-builder/pulp-rules'
+ make -C pulp-rt header pmsis build install BUILD_DIR=/root/pulpissimo/pulp-builder/build/pulp-rt INSTALL_DIR=/root/pulpissimo/pulp-builder/install/ws TARGET_INSTALL_DIR=/root/pulpissimo/pulp-builder/install
make: Entering directory '/root/pulpissimo/pulp-builder/pulp-rt'
make: Nothing to be done for 'header'.
mkdir -p /root/pulpissimo/pulp-builder/install
cp -r ext/pmsis_api/* /root/pulpissimo/pulp-builder/install
/bin/riscv32-unknown-elf-gcc  -march=rv32imcxgap8 -D__riscv__ -I/root/pulpissimo/pulp-builder/pulp-rt/kernel -D__RT_USE_IO=1 -D__RT_USE_ASSERT=1 -Os -g -fno-jump-tables -Werror -fno-tree-loop-distribute-patterns -D__RT_CLUSTER_ASM -D__RT_HYPER_COPY_ASM=1 -D__RT_CPI_COPY_ASM=1 -D__RT_I2C_COPY_ASM=1 -D__RT_SPIM_COPY_ASM=1  -Wextra -Wall -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wundef -fdata-sections -ffunction-sections -I/root/pulpissimo/pulp-builder/install/include/io -I/root/pulpissimo/pulp-builder/install/include -include /root/pulpissimo/pulp-builder/build/pulp-rt/gap_rev1/cl_config.h    -MMD -MP -c kernel/sync_mc.c -o /root/pulpissimo/pulp-builder/build/pulp-rt/gap_rev1/rt/cl/kernel/sync_mc.o
make: /bin/riscv32-unknown-elf-gcc: Command not found
/root/pulpissimo/pulp-builder/build/pulp-rt/gap_rev1/__rules.mk:58: recipe for target '/root/pulpissimo/pulp-builder/build/pulp-rt/gap_rev1/rt/cl/kernel/sync_mc.o' failed
make: *** [/root/pulpissimo/pulp-builder/build/pulp-rt/gap_rev1/rt/cl/kernel/sync_mc.o] Error 127
make: Leaving directory '/root/pulpissimo/pulp-builder/pulp-rt'
 
the path to which i have given is /opt/riscv/bin/

can i know the possible ways to rectify this error

Thanks and regards 
Shilpa

**Comment by haugoug** [comment]
Have you defined PULP_RISCV_GCC_TOOLCHAIN ?
